title: Reema Kumari
#logo: /assets/img/headshot_circle.png
#description: Master’s in information systems/Business Analytics with 5 years of experience in data analytics, reporting/visualization, data 
warehousing, and storytelling. Seeking to leverage technical and interpersonal skills to provide accurate data analysis and growth
strategies for businessdecisions that enhance business development
#show_downloads: true
#theme: jekll-theme-minimal
