title: Reema Kumari
logo: /assets/images/reema_portfolio_circle.png
description: SWE 23 | Seeking Full time for Fall 23 | Data Analyst & Business Intelligence Analyst| Tableau | SQL
show_downloads: true
theme: jekyll-theme-minimal
