title: Reema Kumari
#logo: /assets/img/headshot_circle.png
description: SWE 23 | Data Analytics & Visualization Intern @UT System | Data Analyst & Business Intelligence Analyst| Certified SAP HCM/SuccessFactors consultant| Tableau | SQL | Ex- Capgemini | Seeking Full time for Fall 23
show_downloads: true
theme: jekyll-theme-minimal
